// Code generated by MockGen. DO NOT EDIT.
// Source: listener/changes.go

// Package mock_listener is a generated GoMock package.
package mock_listener

import (
	gomock "github.com/golang/mock/gomock"
	fsnotify "gopkg.in/fsnotify.v1"
	reflect "reflect"
)

// MockIChangesListener is a mock of IChangesListener interface
type MockIChangesListener struct {
	ctrl     *gomock.Controller
	recorder *MockIChangesListenerMockRecorder
}

// MockIChangesListenerMockRecorder is the mock recorder for MockIChangesListener
type MockIChangesListenerMockRecorder struct {
	mock *MockIChangesListener
}

// NewMockIChangesListener creates a new mock instance
func NewMockIChangesListener(ctrl *gomock.Controller) *MockIChangesListener {
	mock := &MockIChangesListener{ctrl: ctrl}
	mock.recorder = &MockIChangesListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIChangesListener) EXPECT() *MockIChangesListenerMockRecorder {
	return m.recorder
}

// CloseWatcher mocks base method
func (m *MockIChangesListener) CloseWatcher() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseWatcher")
}

// CloseWatcher indicates an expected call of CloseWatcher
func (mr *MockIChangesListenerMockRecorder) CloseWatcher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWatcher", reflect.TypeOf((*MockIChangesListener)(nil).CloseWatcher))
}

// ListenEvents mocks base method
func (m *MockIChangesListener) ListenEvents() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenEvents")
}

// ListenEvents indicates an expected call of ListenEvents
func (mr *MockIChangesListenerMockRecorder) ListenEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenEvents", reflect.TypeOf((*MockIChangesListener)(nil).ListenEvents))
}

// isExcludedFile mocks base method
func (m *MockIChangesListener) isExcludedFile(absoluteFile string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isExcludedFile", absoluteFile)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isExcludedFile indicates an expected call of isExcludedFile
func (mr *MockIChangesListenerMockRecorder) isExcludedFile(absoluteFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isExcludedFile", reflect.TypeOf((*MockIChangesListener)(nil).isExcludedFile), absoluteFile)
}

// isModifiedFile mocks base method
func (m *MockIChangesListener) isModifiedFile(e fsnotify.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isModifiedFile", e)
	ret0, _ := ret[0].(bool)
	return ret0
}

// isModifiedFile indicates an expected call of isModifiedFile
func (mr *MockIChangesListenerMockRecorder) isModifiedFile(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isModifiedFile", reflect.TypeOf((*MockIChangesListener)(nil).isModifiedFile), e)
}

// SetupDirectoriesToWatch mocks base method
func (m *MockIChangesListener) SetupDirectoriesToWatch(directory string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupDirectoriesToWatch", directory)
}

// SetupDirectoriesToWatch indicates an expected call of SetupDirectoriesToWatch
func (mr *MockIChangesListenerMockRecorder) SetupDirectoriesToWatch(directory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDirectoriesToWatch", reflect.TypeOf((*MockIChangesListener)(nil).SetupDirectoriesToWatch), directory)
}

// EventHandler mocks base method
func (m *MockIChangesListener) EventHandler(event fsnotify.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventHandler", event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EventHandler indicates an expected call of EventHandler
func (mr *MockIChangesListenerMockRecorder) EventHandler(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventHandler", reflect.TypeOf((*MockIChangesListener)(nil).EventHandler), event)
}
